<?php namespace App\Modules\Gsu\Models;

use Illuminate\Database\Eloquent\Model;
use Input;
use Session;
use DB;


class GsuModel extends Model {

    public function getAllRequest(){
        $sql = <<<EOF
              SELECT RICHIESTE.STATO, RICHIESTE.MANUTENZIONE,  RICHIESTE_EVASE.CODICE_R,  RICHIESTE.DATADOCUMENTO,  RICHIESTE.OGGETTO,  RICHIESTE.DESCRIZIONE AS DESCRCANONE,
                 RICHIESTE.DESCRIZIONE2		AS DESCRCANONE2,
				 RICHIESTE.QUANTITA 		AS QTAAOF70,
				ANAGRAFICA1.DESCRIZIONE 	AS SOGGETTO,
				ANAGRAFICA2.DESCRIZIONE 	AS CLIENTE,
				ANAGRAFICA3.DESCRIZIONE 	AS DESTINATARIOABITUALE,
				RICHIESTE_EVASE.QUANTITA 	AS QTAGSU
			FROM
				gsu.dbo.RICHIESTE_EVASE
				RIGHT OUTER JOIN 	UNIWEB.dbo.AOF70 RICHIESTE  	ON  RICHIESTE_EVASE.CODICE_R  =  RICHIESTE.MANUTENZIONE
				LEFT  OUTER JOIN	UNIWEB.dbo.AGE10 ANAGRAFICA1  ON  RICHIESTE.SOGGETTO 			= ANAGRAFICA1.SOGGETTO
				LEFT  OUTER JOIN	UNIWEB.dbo.AGE10 ANAGRAFICA2  ON  RICHIESTE.CLIENTE 			= ANAGRAFICA2.SOGGETTO
				LEFT  OUTER JOIN	UNIWEB.dbo.AGE10 ANAGRAFICA3  ON  RICHIESTE.DESTINATARIOABITUALE	= ANAGRAFICA3.SOGGETTO
			    WHERE (NOT ( RICHIESTE.OGGETTO LIKE 'TRF%') AND NOT ( RICHIESTE.OGGETTO LIKE 'OR%') AND NOT ( RICHIESTE.OGGETTO LIKE 'NR%') AND NOT ( RICHIESTE.OGGETTO = '' ))
EOF;

        $request  = DB::select($sql);
        $request = json_encode($request);
        return $request;
    }

}

